#两个不同配置文件是操作不同的数据库
#指定服务的端口号
server:
  port: 8003

#数据库连接
#先是要导入一个mysql的依赖
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
  #    配置应用项目名(服务名称)
  application:
    name: provider-article

#这是配置xml文件的路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #这是开始驼峰式命名规则
  configuration:
    map-underscore-to-camel-case: true



eureka:
  #可以修改注册到中心的名称
  instance:
    instance-id: ${spring.application.name}-${server.port}
  client:
    register-with-eureka: true #开启将他注册到eureka的注册中心
    fetch-registry: true #开启获取注册实例列表
    service-url:
       defaultZone: http://localhost:7001/eureka/ #配置注册中心的地址（就是注册中心的地址）
      #这是说将两个服务提供者都注册到eureka中
#      defaultZone: http://r1:7001/eureka/,http://r2:7002/eureka/ #配置注册中心的地址（就是注册中心的地址）

info:
  remark: 这是一个管理系统的文章部分，提供了增删改查
  author: mc

##被监控的hystrix-service服务需要开启Actuator的hystrix.stream端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: 'hystrix.stream' #暴露hystrix监控端点