server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true #获取注册中心列表
    service-url:
      defaultZone: http://r1:7001/eureka/  #配置注册中⼼地址
spring:
  application:
    name: consumer-exam-8080
  thymeleaf:
    prefix: classpath:/templates/views/

info:
  remark: 消费者