#指定服务的端口号
server:
  port: 7001

#配置eureka的名称
spring:
  application:
    name: eureka-server

#配置eureka实例的域名
eureka:
  instance:
    hostname: localhost #相当于是ip地址
  client:
    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: false #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      #      这里是在拼接地址
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      #      r1注册到r2提供者中
      #       defaultZone: http://r2:7002/eureka/
      defaultZone: http://localhost:7001/eureka/
#一般是写域名